<?php

use Illuminate\Database\Seeder;

class TaskSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::table('tasks')->insert([
			[
				'group_id'      => 1,
				'user_id'       => 1,
				'server_id'     => 1,
				'task_title'    => 'PHP脚本文件',
				'task_type'     => 'script',
				'task_lang'     => 'php',
				'commend_type'  => 'file',
				'task_command'  => storage_path('scripts/php_say_hello.php'),
				'task_desc'     => '运行PHP脚本文件测试',
				'task_run_time' => '*/5 * * * *',
				'task_status'   => 1,
				'created_at'    => date('Y-m-d h:i:s'),
				'updated_at'    => date('Y-m-d h:i:s'),
			],
			[
				'group_id'      => 1,
				'user_id'       => 1,
				'server_id'     => 1,
				'task_title'    => 'Python脚本文件',
				'task_type'     => 'script',
				'task_lang'     => 'python',
				'commend_type'  => 'file',
				'task_command'  => storage_path('scripts/python_say_hello.py'),
				'task_desc'     => '运行python脚本文件测试',
				'task_run_time' => '*/5 * * * *',
				'task_status'   => 0,
				'created_at'    => date('Y-m-d h:i:s'),
				'updated_at'    => date('Y-m-d h:i:s'),
			],
			[
				'group_id'      => 1,
				'user_id'       => 1,
				'server_id'     => 1,
				'task_title'    => 'Shell脚本文件',
				'task_type'     => 'script',
				'task_lang'     => 'bash',
				'commend_type'  => 'file',
				'task_command'  => storage_path('scripts/shell_say_hello.sh'),
				'task_desc'     => '运行shell脚本文件测试',
				'task_run_time' => '*/5 * * * *',
				'task_status'   => 1,
				'created_at'    => date('Y-m-d h:i:s'),
				'updated_at'    => date('Y-m-d h:i:s'),
			],
			[
				'group_id'      => 1,
				'user_id'       => 1,
				'server_id'     => 1,
				'task_title'    => 'PHP脚本文件发邮件，不带附件',
				'task_type'     => 'email',
				'task_lang'     => 'php',
				'commend_type'  => 'file',
				'task_command'  => storage_path('scripts/email_pure_text.php'),
				'task_desc'     => '运行PHP脚本文件，产生的内容发送邮件',
				'task_run_time' => '*/5 * * * *',
				'task_status'   => 1,
				'created_at'    => date('Y-m-d h:i:s'),
				'updated_at'    => date('Y-m-d h:i:s'),
			],
			[
				'group_id'      => 1,
				'user_id'       => 1,
				'server_id'     => 1,
				'task_title'    => 'PHP脚本文件发邮件，带有附件',
				'task_type'     => 'email',
				'task_lang'     => 'php',
				'commend_type'  => 'file',
				'task_command'  => storage_path('scripts/email_with_attach.php'),
				'task_desc'     => 'PHP脚本文件发邮件测试，邮件内容带有附件',
				'task_run_time' => '*/5 * * * *',
				'task_status'   => 1,
				'created_at'    => date('Y-m-d h:i:s'),
				'updated_at'    => date('Y-m-d h:i:s'),
			],
			[
				'group_id'      => 1,
				'user_id'       => 1,
				'server_id'     => 1,
				'task_title'    => 'PHP直接命令',
				'task_type'     => 'script',
				'task_lang'     => 'php',
				'commend_type'  => 'command',
				'task_command'  => 'echo "hello"',
				'task_desc'     => '直接输入PHP命令测试',
				'task_run_time' => '*/5 * * * *',
				'task_status'   => 1,
				'created_at'    => date('Y-m-d h:i:s'),
				'updated_at'    => date('Y-m-d h:i:s'),
			],
			[
				'group_id'      => 1,
				'user_id'       => 1,
				'server_id'     => 1,
				'task_title'    => 'Python直接命令',
				'task_type'     => 'script',
				'task_lang'     => 'python',
				'commend_type'  => 'command',
				'task_command'  => 'print("hello")',
				'task_desc'     => '直接输入python命令测试',
				'task_run_time' => '*/5 * * * *',
				'task_status'   => 1,
				'created_at'    => date('Y-m-d h:i:s'),
				'updated_at'    => date('Y-m-d h:i:s'),
			],
			[
				'group_id'      => 1,
				'user_id'       => 1,
				'server_id'     => 1,
				'task_title'    => 'Shell直接命令',
				'task_type'     => 'script',
				'task_lang'     => 'bash',
				'commend_type'  => 'command',
				'task_command'  => 'echo hello',
				'task_desc'     => '直接输入shell命令测试',
				'task_run_time' => '*/5 * * * *',
				'task_status'   => 1,
				'created_at'    => date('Y-m-d h:i:s'),
				'updated_at'    => date('Y-m-d h:i:s'),
			],
		]);
	}
}
